"""
Django settings for dongyanwang_drf project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f_-ezgix808fdj^2&tx-3bd$ihf@+3%dxi1&%krgu4+-91aw-a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'django_filters',
    "django_celery_results",
    "django_celery_beat",
    'corsheaders',  # 添加CORS支持
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件，需要放在最前面
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "api.middleware.request_id.RequestIDMiddleware",
]

ROOT_URLCONF = 'dongyanwang_drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dongyanwang_drf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 指定MySQL引擎
        'NAME': 'dongyan',          # 数据库名
        'USER': 'root',         # MySQL用户名
        'PASSWORD': '123456',     # MySQL密码
        'HOST': 'localhost',                   # 数据库主机（本地为localhost）
        'PORT': '3306',                        # MySQL默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',              # 支持完整Unicode（含emoji）
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式
            'autocommit': True,                # 自动提交事务
        },
        'CONN_MAX_AGE': 300,                   # 连接池存活时间（秒）
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'  # 时区设置

USE_I18N = True

USE_TZ = False  # 修改为fslse，数据库储存北京时间；为true数据库显示UTC时间，前端渲染调用才展示北京时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redis 缓存 & Celery
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CELERY_BROKER_URL = "redis://127.0.0.1:6379/2"
CELERY_RESULT_BACKEND = "django-db"  # django_celery_results
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_BEAT_SCHEDULE = {
    # 每5分钟把热榜刷回数据库（可选）
    "flush_hot_ranks": {
        "task": "api.tasks.flush_hot_ranks",
        "schedule": 300.0,
    },
}

# AUTH_USER_MODEL = 'api.models.user.User'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # "EXCEPTION_HANDLER": "api.utils.exceptions.drf_exception_handler",

    "DEFAULT_THROTTLE_CLASSES": [
        "api.throttles.SlidingWindowAnonThrottle",
        "api.throttles.SlidingWindowUserThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/hour",
        "anon": "200/hour",
    },
}

# OpenSearch/Elasticsearch 直连（选其一）
SEARCH_ENGINE = {
    "BACKEND": "elasticsearch",
    "HOSTS": ["https://localhost:9200"],  # 用 https，因为安全认证启用
    "USER": "elastic",                   # 启动 ES 时显示的用户名
    "PASSWORD": "lWdkp=grtsBFoUVLLL7x", # 启动时生成的密码
    "VERIFY_SSL": False,                 # 如果没配置证书信任，可以先关闭
    "INDEX_PREFIX": "dyw_",
}


# Webhook
WEBHOOK_RETRY = {"max_retries": 5, "retry_backoff": [10, 30, 60, 120, 300]}  # 秒

# 允许文件导出存到 MEDIA_ROOT/exports/
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"
EXPORT_DIR = MEDIA_ROOT / "exports"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)

# 热榜 Key 前缀
HOTSET_PREFIX = "hot:post"  # ZSET: f"{HOTSET_PREFIX}:{model_label}"

# 上传限制（按需微调）
DATA_UPLOAD_MAX_MEMORY_SIZE = 2048 * 1024 * 1024  # 2048MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2048 * 1024 * 1024  # 2048MB


# 简单结构化日志（可接 ELK/Graylog）
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "format": '{"time":"%(asctime)s","level":"%(levelname)s","name":"%(name)s","message":"%(message)s"}'
        },
        "simple": {"format": "%(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}

if not DEBUG:
    # 生产环境用 OSS
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = "你的access_key"
    AWS_SECRET_ACCESS_KEY = "你的secret_key"
    AWS_STORAGE_BUCKET_NAME = "你的bucket"
    AWS_S3_REGION_NAME = "你的region"
    AWS_QUERYSTRING_AUTH = False  # URL 直接访问
else:
    # 开发环境用本地
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

SIMPLE_JWT = {
    # 访问 token 有效期 (比如 30 分钟)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),

    # 刷新 token 有效期 (比如 7 天)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # 是否旋转 refresh token（每次刷新会生成新的 refresh）
    "ROTATE_REFRESH_TOKENS": False,

    # 是否黑名单旧的 refresh token（需要安装 blacklis app）
    "BLACKLIST_AFTER_ROTATION": True,

    # 其他配置保持默认即可
}

AUTH_USER_MODEL = "api.User"

# CORS配置 - 允许前端跨域访问
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React开发服务器默认端口
    "http://127.0.0.1:3000",
    "http://localhost:3001",  # 备用端口
    "http://127.0.0.1:3001",
]

# 允许所有来源（仅开发环境）
CORS_ALLOW_ALL_ORIGINS = DEBUG

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许携带认证信息
CORS_ALLOW_CREDENTIALS = True

# 预检请求缓存时间（秒）
CORS_PREFLIGHT_MAX_AGE = 86400