# Generated by Django 3.2 on 2025-08-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('paper', '论文'), ('project', '项目'), ('competition', '竞赛'), ('internship', '实习')], max_length=20, verbose_name='类型')),
                ('action', models.CharField(max_length=50, verbose_name='动作')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name_plural': '动态',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application', '申请'), ('comment', '评论'), ('like', '点赞')], max_length=20, verbose_name='类型')),
                ('message', models.CharField(max_length=200, verbose_name='消息')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_id', models.PositiveIntegerField(null=True, verbose_name='关联ID')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='兴趣名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='技能名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, verbose_name='平台')),
                ('url', models.URLField(verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.PositiveIntegerField(default=0, verbose_name='论文数')),
                ('projects', models.PositiveIntegerField(default=0, verbose_name='项目数')),
                ('competitions', models.PositiveIntegerField(default=0, verbose_name='竞赛数')),
                ('internships', models.PositiveIntegerField(default=0, verbose_name='实习数')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='粉丝数')),
                ('following', models.PositiveIntegerField(default=0, verbose_name='关注数')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_email',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=100, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, max_length=50, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=80, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(verbose_name='头像'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'password'], name='idx_name_pwd'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.user'),
        ),
        migrations.AddField(
            model_name='usersociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.user'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.user'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.user'),
        ),
    ]
