# Generated by Django 4.2.23 on 2025-09-05 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionspost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='skillpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ConsultationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('sample_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='示例价格')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '咨询申请',
                'verbose_name_plural': '咨询申请',
                'indexes': [models.Index(fields=['user', 'status'], name='api_consult_user_id_c5b1cf_idx'), models.Index(fields=['status', 'created_at'], name='api_consult_status_ab6439_idx')],
                'unique_together': {('user',)},
            },
        ),
    ]
