# Generated by Django 4.2.23 on 2025-09-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_admissionspost_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionspost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='competitionpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='skillpost',
            name='post_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('archived', '已归档')], default='draft', max_length=10),
        ),
    ]
